baseURL = "https://luisfelipegh.github.io"
languageCode = "es"
DefaultContentLanguage = "en"

title = "Luis Felipe Garcia H Â· Software Developer"
theme = "adritian"

[languages]

  [languages.es]
    title = "EspaÃ±ol"
    code = "es"
    weight = 1

    [languages.es.params]
      buttonLanguage = "Idioma"
      homeText = "Inicio"

  [[languages.es.menu.header]]
    name = "Inicio"
    URL = "index.html"
    weight = 1

  [[languages.es.menu.header]]
    name = "Sobre MÃ­"
    URL = "index.html#about"
    weight = 2

  [[languages.es.menu.header]]
    name = "Experiencia"
    URL = "index.html#experience"
    weight = 3

  [[languages.es.menu.header]]
    name = "Contacto"
    URL = "#contact"
    weight = 4

  [[languages.es.menu.footer]]
    name = "ğŸ  Inicio"
    URL = "index.html"
    weight = 1

  [[languages.es.menu.footer]]
    name = "ğŸ’â€â™‚ï¸ Sobre mÃ­"
    URL = "index.html#about"
    weight = 2

  [[languages.es.menu.footer]]
    name = "ğŸ“¨ Contacto"
    URL = "index.html#contact"
    weight = 3


  [languages.en]
    title = "English"
    weight = 2
    code = "en"

    [languages.en.params]
      buttonLanguage = "Language"
      homeText = "Home"

  [[languages.en.menu.header]]
    name = "Home"
    URL = "index.html"
    weight = 1

  [[languages.en.menu.header]]
    name = "About me"
    URL = "index.html#about"
    weight = 2

  [[languages.en.menu.header]]
    name = "Experience"
    URL = "index.html#experience"
    weight = 3

  [[languages.en.menu.header]]
    name = "Contact"
    URL = "#contact"
    weight = 4

  [[languages.en.menu.footer]]
    name = "ğŸ  Home"
    URL = "index.html"
    weight = 1

  [[languages.en.menu.footer]]
    name = "ğŸ’â€â™‚ï¸ About me"
    URL = "index.html#about"
    weight = 2

  [[languages.en.menu.footer]]
    name = "ğŸ“¨ Contact"
    URL = "index.html#contact"
    weight = 2

[build]
  writeStats = true
  
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "css/main.css"
  [[params.plugins.css]]
  link = "css/rad-icons.css"
  [[params.plugins.css]]
  link = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
 


[params]

  sections = ["showcase", "education", "experience", "contact"]
  googleTagManagerID = "GTM-582JNJ4" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "LuisFelipe"
    text2 = "GarciaH"

  [params.footer]
      copyright = "Â© Luis Felipe Garcia H. - 2023"
